nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:8100', 'http://localhost:5173', 'http://127.0.0.1:8100', 'http://127.0.0.1:5173', 'http://192.168.28.52:5173', 'capacitor://localhost', 'ionic://localhost', 'http://localhost:8000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api':
            allow_origin: ['http://localhost:8100', 'http://localhost:5173', 'http://127.0.0.1:8100', 'http://127.0.0.1:5173', 'http://192.168.28.52:5173', 'capacitor://localhost', 'ionic://localhost', 'http://localhost:8000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
